"use strict";

module.exports = {
	extends: require.resolve("./babel"),
	plugins: [
		"react",
	],
	rules: {
		"react/boolean-prop-naming": ["warn", { "rule": "/^((?!(is|has)[A-Z]).)*/" }],
		"react/default-props-match-prop-types": "warn",
		"react/display-name": "warn",
		"react/forbid-component-props": "off",
		"react/forbid-elements": "off",
		"react/forbid-prop-types": "warn",
		"react/forbid-foreign-prop-types": "warn",
		"react/no-array-index-key": "warn",
		"react/no-children-prop": "error",
		"react/no-danger": "off",
		"react/no-danger-with-children": "error",
		"react/no-deprecated": "error",
		"react/no-did-mount-set-state": "warn",
		"react/no-did-update-set-state": "warn",
		"react/no-direct-mutation-state": "warn",
		"react/no-find-dom-node": "warn",
		"react/no-is-mounted": "error",
		"react/no-multi-comp": "off",
		"react/no-redundant-should-component-update": "error",
		"react/no-render-return-value": "error",
		"react/no-set-state": "warn",
		"react/no-typos": "warn",
		"react/no-string-refs": "error",
		"react/no-unescaped-entities": "error",
		"react/no-unknown-property": "warn",
		"react/no-unused-prop-types": "warn",
		"react/no-unused-state": "warn",
		"react/no-will-update-set-state": "warn",
		"react/prefer-es6-class": "warn",
		"react/prefer-stateless-function": "warn",
		"react/prop-types": "warn",
		"react/react-in-jsx-scope": "error",
		"react/require-default-props": "error",
		"react/require-optimization": "off",
		"react/require-render-return": "error",
		"react/self-closing-comp": "off",
		"react/sort-comp": "off",
		"react/sort-prop-types": "off",
		"react/style-prop-object": "warn",
		"react/void-dom-elements-no-children": "warn",

		"react/jsx-boolean-value": "warn",
		"react/jsx-closing-bracket-location": "warn",
		"react/jsx-closing-tag-location": "warn",
		"react/jsx-curly-spacing": "warn",
		"react/jsx-equals-spacing": "warn",
		"react/jsx-filename-extension": "off",
		"react/jsx-first-prop-new-line": "off",
		"react/jsx-handler-names": "warn",
		"react/jsx-indent": ["warn", "tab"],
		"react/jsx-indent-props": ["warn", "tab"],
		"react/jsx-key": "warn",
		"react/jsx-max-props-per-line": "off",
		"react/jsx-no-bind": "off",
		"react/jsx-no-comment-textnodes": "warn",
		"react/jsx-no-duplicate-props": "error",
		"react/jsx-no-literals": "off",
		"react/jsx-no-target-blank": "off",
		"react/jsx-no-undef": "warn",
		"react/jsx-pascal-case": "warn",
		"react/jsx-sort-props": "off",
		"react/jsx-space-before-closing": "warn",
		"react/jsx-tag-spacing": "warn",
		"react/jsx-uses-react": "warn",
		"react/jsx-uses-vars": "warn",
		"react/jsx-wrap-multilines": "warn",
	},
};
