"use strict";

module.exports = {
	rules: {
		"no-await-in-loop": "warn",
		"no-cond-assign": ["error", "except-parens"],
		"no-console": "warn",
		"no-constant-condition": ["warn", { "checkLoops": false }],
		"no-control-regex": "error",
		"no-debugger": "warn",
		"no-dupe-args": "error",
		"no-dupe-keys": "error",
		"no-duplicate-case": "error",
		"no-empty-character-class": "error",
		"no-empty": "warn",
		"no-ex-assign": "error",
		"no-extra-boolean-cast": "error",
		"no-extra-parens": "off",
		"no-extra-semi": "error",
		"no-func-assign": "error",
		"no-inner-declarations": ["error", "functions"],
		"no-invalid-regexp": "error",
		"no-irregular-whitespace": "error",
		"no-obj-calls": "error",
		"no-prototype-builtins": "off",
		"no-regex-spaces": "error",
		"no-sparse-arrays": "error",
		"no-template-curly-in-string": "warn",
		"no-unexpected-multiline": "error",
		"no-unreachable": "warn",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "error",
		"use-isnan": "error",
		"valid-jsdoc": "warn",
		"valid-typeof": "error",
	},
};
