"use strict";

module.exports = {
	rules: {
		"array-bracket-spacing": ["warn", "never"],
		"block-spacing": ["warn", "always"],
		"brace-style": ["warn", "stroustrup", { "allowSingleLine": true }],
		"camelcase": "warn",
		"comma-dangle": ["warn", "always-multiline"],
		"comma-spacing": ["warn", { "before": false, "after": true }],
		"comma-style": ["warn", "last"],
		"computed-property-spacing": ["warn", "never"],
		"consistent-this": "error",
		"eol-last": "off",
		"func-names": "off",
		"func-style": "off",
		"id-blacklist": "off",
		"id-length": "off",
		"id-match": "off",
		"indent": ["warn", "tab", { "SwitchCase": 1 }],
		"jsx-quotes": "warn",
		"key-spacing": ["warn", { "afterColon": true }],
		"keyword-spacing": "warn",
		"linebreak-style": ["warn", "unix"],
		"lines-around-comment": "off",
		"max-depth": "off",
		"max-len": ["warn", 80, 1],
		"max-lines": "off",
		"max-nested-callbacks": "off",
		"max-params": "off",
		"max-statements": "off",
		"max-statements-per-line": "off",
		"new-cap": "warn",
		"new-parens": "warn",
		"newline-after-var": "off",
		"newline-before-return": "off",
		"newline-per-chained-call": "off",
		"no-array-constructor": "warn",
		"no-bitwise": "warn",
		"no-continue": "off",
		"no-inline-comments": "off",
		"no-lonely-if": "off",
		"no-mixed-operators": "warn",
		"no-mixed-spaces-and-tabs": ["warn", "smart-tabs"],
		"no-multiple-empty-lines": ["warn", { "max": 2 }],
		"no-negated-condition": "off",
		"no-nested-ternary": "warn",
		"no-new-object": "warn",
		"no-plusplus": "off",
		"no-restricted-syntax": "off",
		"no-spaced-func": "warn",
		"no-ternary": "off",
		"no-trailing-spaces": "warn",
		"no-underscore-dangle": "off",
		"no-unneeded-ternary": "warn",
		"no-whitespace-before-property": "warn",
		"object-curly-newline": "off",
		"object-curly-spacing": ["warn", "always", {
			"objectsInObjects": false,
			"arraysInObjects": false,
		}],
		"object-property-newline": "off",
		"one-var": "off",
		"one-var-declaration-per-line": "off",
		"operator-assignment": "off",
		"operator-linebreak": ["warn", "after", {
			"overrides": { "?": "before", ":": "before" },
		}],
		"padded-blocks": ["warn", "never"],
		"quote-props": "off",
		"quotes": ["warn", "double", "avoid-escape"],
		"require-jsdoc": "off",
		"semi": ["warn", "always"],
		"semi-spacing": ["warn", { "after": true }],
		"sort-vars": "off",
		"space-before-blocks": "warn",
		"space-before-function-paren": ["warn", {
			"anonymous": "always",
			"named": "never",
		}],
		"space-in-parens": ["warn", "never"],
		"space-infix-ops": "warn",
		"space-unary-ops": "warn",
		"spaced-comment": ["warn", "always", {
			"line": {
				"markers": ["/"],
			},
		}],
		"unicode-bom": "error",
		"wrap-regex": "off",
	},
};
